[package]
name = "ch"
version = "0.1.0"
authors = ["Gnanesh <gnaneshkunal@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.20.0"